name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Testing packages
      run: make test

    - name: Building app
      run: make build

    - name: Running app
      run: make start-kind
